---
- name: Sign ssh key
  hosts: all
  gather_facts: no

  tasks:
  - name: "Sign SSH key"
    delegate_to: localhost
    signssh:
      vault_addr: "{{ vault_addr }}"
      vault_token: "{{ vault_token }}"
      method: "test"
      params: 
        remark: "ansible"

    register: signssh
  - name: "Debug signssh"
    debug:
      var: signssh
