---
- name: Sign ssh key
  hosts: all
  gather_facts: no

  tasks:
  - name: "Tell subsequent tasks to use our deploy virtualenv"
    set_fact:
     ansible_python_interpreter: /root/venv/bin/python
    tags:
     - always

  - name: "Sign SSH key"
    delegate_to: localhost
    signssh:
      vault_addr: "{{ vault_addr }}"
      vault_token: "{{ vault_token }}"
      method: "test"
      params: 
        remark: "ansible"

    register: signssh
  - name: "Debug signssh"
    debug:
      var: signssh
