---
- name: zabbix_agent
  hosts: all
  gather_facts: yes
  vars:
     templates:
      - "Template OS Linux"

  tasks:


  - name: "Sign SSH key"
    delegate_to: localhost
    signssh:
      vault_addr: "{{ vault_addr }}"
      vault_token: "{{ vault_token }}"
      method: "test"
      params: 
        remark: "ansible"
        
  - name: "zabbixclient | Get all clients"
    delegate_to: localhost
    zabbix_json_rpc:
      hostname: "{{ zabbixhost }}"
      token: "{{ zabbixtoken }}"
      method: host.get
      params:
        output: "extend"
        filter: 
          host: 
            "{{ inventory_hostname }}"
    register: zabbix_result

  - name: "zabbixclient | Create client if not exists"
    delegate_to: localhost
    zabbix_json_rpc:
      hostname: "{{ zabbixhost }}"
      token: "{{ zabbixtoken }}"
      method: host.create
      params:
        host: "{{ inventory_hostname }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_default_ipv4.address }}"
            dns: ""
            port: 10050
        groups:
          - groupid: 2
        templates:
          - templateid: "{{ item }}"
      var: zabbix_result


