---
- name: zabbix_agent
  hosts: all
  gather_facts: no
  vars:
     templates:
      - "Template OS Linux"

  tasks:
  - name: "zabbixclient | Get all clients"
    delegate_to: localhost
    zabbix_json_rpc:
      hostname: "{{ zabbixhost }}"
      token: "{{ zabbixtoken }}"
      method: host.get
      params:
        output: "extend"
        filter: 
          host: 
            "{{ ansible_inventory }}"
    register: zabbix_result

  - name: "Debug"
    debug:
      var: zabbix_result


